<?php

$options = array();
$options['salt'] = array('name' => __('DB Security Salt', 'plugin-check'),
    'type' => 'hidden',
    'help' => __('Not visible to the end user', 'plugin-check'));

$options['show_source'] = array('name' => __('Show Source', 'plugin-check'),
    'type' => 'checkbox',
    'value' => true,
    'help' => __('Show the autogenerated source code that is used for detecting undefined functions and methods. Useful only for debugging.', 'plugin-check'));

$options['show_defined'] = array('name' => __('Show Defined Functions', 'plugin-check'),
    'type' => 'checkbox',
    'value' => false,
    'help' => __('By default, PHP Psuedo Compiler shows only undefined functions and methods. Check this option to view defined ones as well.', 'plugin-check'));

$options['show_tokens'] = array('name' => __('Show Detected Tokens', 'plugin-check'),
    'type' => 'checkbox',
    'value' => false,
    'help' => __('If you want to see the functions and methods detected from the files, enable this option. It is useful for debugging purposes.', 'plugin-check'));

$options['show_google_translate'] = array('name' => __('Enable Google Translation of Admin Pages?', 'plugin-check'),
    'help' => __('This plugin can display its admin pages using Google Translate. If you would like to see the pages in your language, please enable this option. You will then see a language selector near the top right corner where you can choose your language.', 'plugin-check'),
    'type' => 'checkbox',
    'reload' => true,
    'value' => false);
$options['dynamic_menu'] = array('name' => __('Enable Dynamic Menu?', 'plugin-check'),
    'type' => 'checkbox',
    'help' => __('By default, the menu on the admin pages expands on hover, which you may find annoying in the standalone mode. You can disable the feature here.', 'plugin-check'),
    'value' => true,
    'reload' => true);
